N = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(N))
print('É alpha numérico: ', N.isalnum())
print('É alfabeto: ', N.isalpha())
print('É ASCII: ', N.isascii())
print('É decimal: ', N.isdecimal())
print('É um digito: ', N.isdigit())
print('É um indentificador: ', N.isidentifier())
print('É minúsculo: ', N.islower())
print('É númerico: ', N.isnumeric())
print('É possível imprimir: ', N.isprintable())
print('É um espaço: ', N.isspace())
print('É um espaço: ', N.istitle())
print('É maiúsculo: ', N.isupper())
